const axios = require('axios');

const config = {
    provider: process.env.AI_PROVIDER || 'huggingface',
    huggingface: {
        apiUrl:
            'https://router.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.3',
        apiKey: process.env.HUGGINGFACE_API_KEY || ''
    },
    openrouter: {
        apiUrl: 'https://openrouter.ai/api/v1/chat/completions',
        apiKey: process.env.OPENROUTER_API_KEY || '',
        model: 'mistralai/mistral-7b-instruct:free'
    }
};

function cleanAIText(t) {
    t = t.trim().replace(/\s+/g, ' ');
    if (/^(Here.?s|This is)/i.test(t)) t = t.replace(/^.*?:\s*/, '');
    if (!/[.!?]$/.test(t)) t += '.';
    return t.trim();
}

const SYSTEM_PROMPT = `Generate a unique, original typing practice paragraph.

Requirements:
1. Length: 40–80 words.
2. Topic: Randomly choose a different theme each time (technology, travel, daily life, space, nature, creativity, emotions, business, learning, etc.).
3. Style: Natural human writing with clear structure.
4. Variation:
   - Each paragraph MUST differ in tone, topic, word choice, and sentence structure from previous outputs.
   - Avoid repeating common phrases like “typing practice,” “this paragraph,” or meta references about generating text.
5. Readability: 6th–9th grade reading level.
6. No copyrighted content, no quotes, no reused sentences from known books or articles.
7. Avoid overly technical or specialized terminology.
8. Do NOT mention that this was generated by AI.

Output ONLY the raw paragraph text. No titles, no bullet points, no introductions.`;

async function genHF() {
    const headers = {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${config.huggingface.apiKey}`
    };

    // Use the OpenAI-compatible endpoint
    const url = 'https://router.huggingface.co/v1/chat/completions';

    const resp = await axios.post(
        url,
        {
            model: 'meta-llama/Meta-Llama-3-8B-Instruct',
            messages: [
                { role: 'system', content: 'You are a creative writing assistant.' },
                { role: 'user', content: SYSTEM_PROMPT }
            ],
            max_tokens: 200
        },
        { headers }
    );

    return cleanAIText(resp.data.choices?.[0]?.message?.content || '');
}

async function genOR() {
    const resp = await axios.post(
        config.openrouter.apiUrl,
        {
            model: config.openrouter.model,
            messages: [
                { role: 'system', content: 'You are a creative writing assistant.' },
                { role: 'user', content: SYSTEM_PROMPT }
            ]
        },
        {
            headers: {
                Authorization: `Bearer ${config.openrouter.apiKey}`,
                'Content-Type': 'application/json'
            }
        }
    );

    return cleanAIText(resp.data.choices?.[0]?.message?.content || '');
}

function fallback() {
    return 'Typing accurately is a skill that improves with practice. Start slowly, focus on precision, and gradually increase speed.';
}

async function generateAIParagraph() {
    try {
        if (config.provider === 'openrouter' && config.openrouter.apiKey) {
            return await genOR();
        } else if (config.huggingface.apiKey) {
            return await genHF();
        } else {
            // If no keys, use fallback or try free endpoint if available
            // For now, just fallback to avoid errors
            console.log("No AI keys configured, using fallback text.");
            return fallback();
        }
    } catch (err) {
        console.error('AI generation failed:', err.message);
        if (err.response) {
            console.error('Status:', err.response.status);
            console.error('Data:', JSON.stringify(err.response.data));
        }
        return fallback();
    }
}

module.exports = { generateAIParagraph };
